<a href="https://colab.research.google.com/github/Carlos051068/Colab_aula_Anhanguera/blob/main/dinheiroemcirculacaocsv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=100&$format=text/csv&$select=Quantidade,Denominacao,Especie
#Anhanguera DINHEIRO EM CIRCULAÇÃO

import pandas as pd

pd.read_csv("https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=100&$format=text/csv&$select=Data,Quantidade,Denominacao,Especie").head()

         Data  Quantidade  Denominacao Especie
0  1994-10-03   692701959         0.01  Moedas
1  1994-10-03   462277579         0.05  Moedas
2  1994-10-03   404559065         0.10  Moedas
3  1994-10-03     1492870         0.25  Moedas
4  1994-10-03   278901842         0.50  Moedas