<a href="https://colab.research.google.com/github/Carlos051068/Colab_aula_Anhanguera/blob/main/json_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#Leitura de JSON e CSV com pandas

#Estamos usando o método read_json para carregar dados de uma API.
#Veja que estamos passando o caminho para o método. Nessa fonte de dados,
#são encontradas a taxa selic de cada dia.

import pandas as pd

pd.read_json("https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=json").head()

         data     valor
0  04/06/1986  0.065041
1  05/06/1986  0.067397
2  06/06/1986  0.066740
3  09/06/1986  0.068247
4  10/06/1986  0.067041

In [14]:
#o método retorna que o DF possui x registros (entradas) e 2 colunas. Os índices são numéricos e variam de 0 a (N-1).
#Esse método retorna sobre a quantidade de células sem valor (non-null) e o tipo dos dados nas colunas.
#Como podemos ver, ambas colunas possuem x valores não nulos, como esse número é igual a quantidade de linhas,
#então não existem valores faltantes. Quanto ao tipo de dados, o "data" é um object,
#são todos do tipo strings ou existe mistura de tipos; "valor" é um float.
 
df_selic = pd.read_json("https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=json")

print(df_selic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9093 entries, 0 to 9092
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    9093 non-null   object
 1   valor   9093 non-null   float64
dtypes: float64(1), object(1)
memory usage: 142.2+ KB
None

In [11]:
#https://www.youtube.com/watch?v=GGkUt4hy0T8
#API do Banco Central com Python - APIs com Paginação
#Leitura de JSON e CSV com pandas

#Estamos usando o método read_json para carregar dados de uma API.
#Veja que estamos passando o caminho para o método. Nessa fonte de dados,
#são encontradas a taxa selic de cada dia.
#https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=100&$format=json&$select=Quantidade,Denominacao,Especie

import pandas as pd

pd.read_json("https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=10&$format=json&$select=Quantidade,Denominacao,Especie").head()

,@odata.context,value
0,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Quantidade': 692701959, 'Denominacao': '0.01..."
1,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Quantidade': 462277579, 'Denominacao': '0.05..."
2,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Quantidade': 404559065, 'Denominacao': '0.10..."
3,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Quantidade': 1492870, 'Denominacao': '0.25',..."
4,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Quantidade': 278901842, 'Denominacao': '0.50..."